/* 
 * ECE 461 - Fall 2021 - Project 2
 *
 * API for ECE 461/Fall 2021/Project 2: A Trustworthy Module Registry
 *
 * OpenAPI spec version: 3.0.2
 * Contact: davisjam@purdue.edu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PackageData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PackageDataTests
    {
        // TODO uncomment below to declare an instance variable for PackageData
        //private PackageData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PackageData
            //instance = new PackageData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PackageData
        /// </summary>
        [Test]
        public void PackageDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PackageData
            //Assert.IsInstanceOfType<PackageData> (instance, "variable 'instance' is a PackageData");
        }


        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'URL'
        /// </summary>
        [Test]
        public void URLTest()
        {
            // TODO unit test for the property 'URL'
        }
        /// <summary>
        /// Test the property 'JSProgram'
        /// </summary>
        [Test]
        public void JSProgramTest()
        {
            // TODO unit test for the property 'JSProgram'
        }

    }

}
