/* 
 * ECE 461 - Fall 2021 - Project 2
 *
 * API for ECE 461/Fall 2021/Project 2: A Trustworthy Module Registry
 *
 * OpenAPI spec version: 3.0.2
 * Contact: davisjam@purdue.edu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PackageRating
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PackageRatingTests
    {
        // TODO uncomment below to declare an instance variable for PackageRating
        //private PackageRating instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PackageRating
            //instance = new PackageRating();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PackageRating
        /// </summary>
        [Test]
        public void PackageRatingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PackageRating
            //Assert.IsInstanceOfType<PackageRating> (instance, "variable 'instance' is a PackageRating");
        }


        /// <summary>
        /// Test the property 'BusFactor'
        /// </summary>
        [Test]
        public void BusFactorTest()
        {
            // TODO unit test for the property 'BusFactor'
        }
        /// <summary>
        /// Test the property 'Correctness'
        /// </summary>
        [Test]
        public void CorrectnessTest()
        {
            // TODO unit test for the property 'Correctness'
        }
        /// <summary>
        /// Test the property 'RampUp'
        /// </summary>
        [Test]
        public void RampUpTest()
        {
            // TODO unit test for the property 'RampUp'
        }
        /// <summary>
        /// Test the property 'ResponsiveMaintainer'
        /// </summary>
        [Test]
        public void ResponsiveMaintainerTest()
        {
            // TODO unit test for the property 'ResponsiveMaintainer'
        }
        /// <summary>
        /// Test the property 'LicenseScore'
        /// </summary>
        [Test]
        public void LicenseScoreTest()
        {
            // TODO unit test for the property 'LicenseScore'
        }
        /// <summary>
        /// Test the property 'GoodPinningPractice'
        /// </summary>
        [Test]
        public void GoodPinningPracticeTest()
        {
            // TODO unit test for the property 'GoodPinningPractice'
        }

    }

}
